<a href="https://colab.research.google.com/github/moraesleonardo/NumPy/blob/main/NumPy_Udemy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Arrays

In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.75926638, 0.07243832, 0.00137914, 0.13725577, 0.36400825])

In [16]:
np.random.rand(5, 5)

array([[0.90007042, 0.11602397, 0.56472881, 0.57535402, 0.05432708],
       [0.19539629, 0.67031895, 0.524683  , 0.68450108, 0.0424378 ],
       [0.2990191 , 0.56090546, 0.40621416, 0.95169575, 0.34765358],
       [0.58165865, 0.45902158, 0.40263443, 0.18939512, 0.70667048],
       [0.33766634, 0.7663613 , 0.78446495, 0.41148525, 0.31337129]])

In [17]:
np.random.randn(2) #normal distribution

array([ 0.39428992, -0.28368358])

In [18]:
np.random.randn(4, 4) #normal distribution

array([[ 0.4675358 , -0.98050148,  0.58637483, -1.09712344],
       [ 0.75401597,  1.25582152, -0.13341326, -1.11022083],
       [ 0.78566566, -0.88751162,  0.86768581, -0.39635251],
       [-0.19133475,  0.29041406,  0.2493351 ,  0.79269156]])

In [19]:
np.random.randint(1, 100, 10)

array([99, 30, 31, 88, 21, 32, 64, 44, 31, 46])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0, 50, 10)

In [23]:
ranarr

array([17,  9, 42,  4, 13, 40,  9,  9, 11, 27])

In [24]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr.max()

42

In [26]:
ranarr.min()

4

In [27]:
ranarr

array([17,  9, 42,  4, 13, 40,  9,  9, 11, 27])

In [28]:
ranarr.argmax()

2

In [29]:
ranarr.argmin()

3

In [30]:
arr.shape

(25,)

In [31]:
arr = arr.reshape(5, 5)

In [32]:
arr.shape

(5, 5)

In [33]:
arr.dtype

dtype('int64')

In [34]:
from numpy.random import randint

In [35]:
randint(2, 10)

8

In [36]:
arr = np.arange(0, 11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[8]

8

In [39]:
arr[1:5]

array([1, 2, 3, 4])

In [40]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [41]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [42]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[0:5] = 100

In [44]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
arr = np.arange(0, 11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
slice_of_arr = arr[0:6]

In [48]:
slice_of_arr[:] = 99

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
arr_copy = arr.copy()

In [51]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
arr_copy[:] = 100

In [53]:
arr_copy


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [56]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [57]:
arr_2d[0][0]

5

In [58]:
arr_2d[0]

array([ 5, 10, 15])

In [59]:
arr_2d[1][2]

30

In [60]:
arr_2d[1, 2]

30

In [61]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [62]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [65]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [66]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
arr_2d[1:3, ]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [68]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

NumPy Operations

- Array with Array
- Array with Scalars
- Universal Array Functions

In [69]:
arr = np.arange(0, 11)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [74]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [75]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [76]:
1/0

ZeroDivisionError: ignored

In [77]:
arr / arr

<ipython-input-77-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [78]:
1 / arr

<ipython-input-78-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [79]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [80]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [81]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [82]:
np.max(arr)

10

In [83]:
arr.max()

10

In [84]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [85]:
np.log(arr)

<ipython-input-85-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])